//Autogenerated triple quantized liym file with draw function
int comicpanelDtricount = 2;
f32 comicpanelDvertpos[] ATTRIBUTE_ALIGN(32) = {0.274624, -0.125453, 0.000276, 0.017912, 0.131258, 0.000276, 0.017912, -0.125453, 0.000276, 0.274624, 0.131258, 0.000276};
uint16_t comicpanelDvertposidx[] = {0,1,2,0,3,1};
f32 comicpanelDtexcord[] ATTRIBUTE_ALIGN(32) = {1.000000, 1.000000, 0.000000, 0.000000, 0.000000, 1.000000, 1.000000, 0.000000};
uint16_t comicpanelDtexcordidx[] = {0,1,2,0,3,1};

void ag_draw_comicpanelD(int vtxfmt) {
	GX_SetArray(GX_VA_POS, &comicpanelDvertpos[0], 12);
	GX_SetArray(GX_VA_TEX0, &comicpanelDtexcord[0], 8);
	drawArrConfig(LV_VPIDX16 | LV_TCIDX16, comicpanelDtricount, vtxfmt,
		NULL, NULL, comicpanelDvertposidx,
		NULL, NULL, NULL,
		NULL, NULL, comicpanelDtexcordidx,
		NULL,
		NULL);
}

void ag_config_comicpanelD(int vtxfmt) {
	liy_VtxDescConfig(LV_VPIDX16 | LV_TCIDX16, vtxfmt);
}