//Autogenerated triple quantized liym file with draw function
int comicpanelEtricount = 2;
f32 comicpanelEvertpos[] ATTRIBUTE_ALIGN(32) = {0.276905, -0.415434, 0.000276, -0.273236, -0.158723, 0.000276, -0.273236, -0.415434, 0.000276, 0.276905, -0.158723, 0.000276};
uint16_t comicpanelEvertposidx[] = {0,1,2,0,3,1};
f32 comicpanelEtexcord[] ATTRIBUTE_ALIGN(32) = {1.000000, 1.000000, 0.000000, 0.000000, 0.000000, 1.000000, 1.000000, 0.000000};
uint16_t comicpanelEtexcordidx[] = {0,1,2,0,3,1};

void ag_draw_comicpanelE(int vtxfmt) {
	GX_SetArray(GX_VA_POS, &comicpanelEvertpos[0], 12);
	GX_SetArray(GX_VA_TEX0, &comicpanelEtexcord[0], 8);
	drawArrConfig(LV_VPIDX16 | LV_TCIDX16, comicpanelEtricount, vtxfmt,
		NULL, NULL, comicpanelEvertposidx,
		NULL, NULL, NULL,
		NULL, NULL, comicpanelEtexcordidx,
		NULL,
		NULL);
}

void ag_config_comicpanelE(int vtxfmt) {
	liy_VtxDescConfig(LV_VPIDX16 | LV_TCIDX16, vtxfmt);
}