//Autogenerated triple quantized liym file with draw function
int comicpanelAtricount = 2;
f32 comicpanelAvertpos[] ATTRIBUTE_ALIGN(32) = {-0.016943, 0.166521, 0.000276, -0.273655, 0.423233, 0.000276, -0.273655, 0.166521, 0.000276, -0.016943, 0.423233, 0.000276};
uint16_t comicpanelAvertposidx[] = {0,1,2,0,3,1};
f32 comicpanelAtexcord[] ATTRIBUTE_ALIGN(32) = {1.000000, 1.000000, 0.000000, 0.000000, 0.000000, 1.000000, 1.000000, 0.000000};
uint16_t comicpanelAtexcordidx[] = {0,1,2,0,3,1};

void ag_draw_comicpanelA(int vtxfmt) {
	GX_SetArray(GX_VA_POS, &comicpanelAvertpos[0], 12);
	GX_SetArray(GX_VA_TEX0, &comicpanelAtexcord[0], 8);
	drawArrConfig(LV_VPIDX16 | LV_TCIDX16, comicpanelAtricount, vtxfmt,
		NULL, NULL, comicpanelAvertposidx,
		NULL, NULL, NULL,
		NULL, NULL, comicpanelAtexcordidx,
		NULL,
		NULL);
}

void ag_config_comicpanelA(int vtxfmt) {
	liy_VtxDescConfig(LV_VPIDX16 | LV_TCIDX16, vtxfmt);
}