//Autogenerated triple quantized liym file with draw function
int comicpanelBtricount = 2;
f32 comicpanelBvertpos[] ATTRIBUTE_ALIGN(32) = {0.274624, 0.166521, 0.000276, 0.017912, 0.423233, 0.000276, 0.017912, 0.166521, 0.000276, 0.274624, 0.423233, 0.000276};
uint16_t comicpanelBvertposidx[] = {0,1,2,0,3,1};
f32 comicpanelBtexcord[] ATTRIBUTE_ALIGN(32) = {1.000000, 1.000000, 0.000000, 0.000000, 0.000000, 1.000000, 1.000000, 0.000000};
uint16_t comicpanelBtexcordidx[] = {0,1,2,0,3,1};

void ag_draw_comicpanelB(int vtxfmt) {
	GX_SetArray(GX_VA_POS, &comicpanelBvertpos[0], 12);
	GX_SetArray(GX_VA_TEX0, &comicpanelBtexcord[0], 8);
	drawArrConfig(LV_VPIDX16 | LV_TCIDX16, comicpanelBtricount, vtxfmt,
		NULL, NULL, comicpanelBvertposidx,
		NULL, NULL, NULL,
		NULL, NULL, comicpanelBtexcordidx,
		NULL,
		NULL);
}

void ag_config_comicpanelB(int vtxfmt) {
	liy_VtxDescConfig(LV_VPIDX16 | LV_TCIDX16, vtxfmt);
}