//Autogenerated triple quantized liym file with draw function
int comicpanelCtricount = 2;
f32 comicpanelCvertpos[] ATTRIBUTE_ALIGN(32) = {-0.016943, -0.125947, 0.000276, -0.273655, 0.130765, 0.000276, -0.273655, -0.125947, 0.000276, -0.016943, 0.130765, 0.000276};
uint16_t comicpanelCvertposidx[] = {0,1,2,0,3,1};
f32 comicpanelCtexcord[] ATTRIBUTE_ALIGN(32) = {1.000000, 1.000000, 0.000000, 0.000000, 0.000000, 1.000000, 1.000000, 0.000000};
uint16_t comicpanelCtexcordidx[] = {0,1,2,0,3,1};

void ag_draw_comicpanelC(int vtxfmt) {
	GX_SetArray(GX_VA_POS, &comicpanelCvertpos[0], 12);
	GX_SetArray(GX_VA_TEX0, &comicpanelCtexcord[0], 8);
	drawArrConfig(LV_VPIDX16 | LV_TCIDX16, comicpanelCtricount, vtxfmt,
		NULL, NULL, comicpanelCvertposidx,
		NULL, NULL, NULL,
		NULL, NULL, comicpanelCtexcordidx,
		NULL,
		NULL);
}

void ag_config_comicpanelC(int vtxfmt) {
	liy_VtxDescConfig(LV_VPIDX16 | LV_TCIDX16, vtxfmt);
}